
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ESPACO_BRANCO = 2;
  public static final int IGUALDADE = 27;
  public static final int OP_DIVI = 20;
  public static final int DL_END = 28;
  public static final int COMENT_MULTI = 35;
  public static final int TIPO_STRING = 6;
  public static final int OP_MULTI = 19;
  public static final int OP_MENORQ = 23;
  public static final int DL_LCHAVE = 31;
  public static final int OP_MAIORQ = 24;
  public static final int IDENTIFICADOR = 3;
  public static final int DL_LPAREN = 29;
  public static final int KEY_WHILE = 11;
  public static final int DL_RCHAVE = 32;
  public static final int OP_DIFE = 22;
  public static final int DL_RPAREN = 30;
  public static final int DL_VIRGUL = 33;
  public static final int EOF = 0;
  public static final int NUMERO_INT = 36;
  public static final int error = 1;
  public static final int KEY_VOID = 8;
  public static final int KEY_PRIVATE = 15;
  public static final int TIPO_INT = 4;
  public static final int COMENT_SINGLE = 34;
  public static final int OP_MINUS = 18;
  public static final int KEY_RETURN = 16;
  public static final int KEY_FOR = 12;
  public static final int KEY_ELSE = 10;
  public static final int OP_IGUAL = 21;
  public static final int KEY_IF = 9;
  public static final int OP_MENOR_IGUAL = 26;
  public static final int TIPO_FLOAT = 5;
  public static final int OP_MAIOR_IGUAL = 25;
  public static final int TIPO_BOOL = 7;
  public static final int OP_MAIS = 17;
  public static final int NUMERO_FLOAT = 37;
  public static final int KEY_PUBLIC = 14;
  public static final int KEY_CLASS = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ESPACO_BRANCO",
  "IDENTIFICADOR",
  "TIPO_INT",
  "TIPO_FLOAT",
  "TIPO_STRING",
  "TIPO_BOOL",
  "KEY_VOID",
  "KEY_IF",
  "KEY_ELSE",
  "KEY_WHILE",
  "KEY_FOR",
  "KEY_CLASS",
  "KEY_PUBLIC",
  "KEY_PRIVATE",
  "KEY_RETURN",
  "OP_MAIS",
  "OP_MINUS",
  "OP_MULTI",
  "OP_DIVI",
  "OP_IGUAL",
  "OP_DIFE",
  "OP_MENORQ",
  "OP_MAIORQ",
  "OP_MAIOR_IGUAL",
  "OP_MENOR_IGUAL",
  "IGUALDADE",
  "DL_END",
  "DL_LPAREN",
  "DL_RPAREN",
  "DL_LCHAVE",
  "DL_RCHAVE",
  "DL_VIRGUL",
  "COMENT_SINGLE",
  "COMENT_MULTI",
  "NUMERO_INT",
  "NUMERO_FLOAT"
  };
}

