
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO_FLOAT = 7;
  public static final int error = 1;
  public static final int NUMERO_INT = 6;
  public static final int IDENTIFICADOR = 3;
  public static final int KEYWORD = 2;
  public static final int DELIMITADOR = 5;
  public static final int OPERADOR = 4;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "KEYWORD",
  "IDENTIFICADOR",
  "OPERADOR",
  "DELIMITADOR",
  "NUMERO_INT",
  "NUMERO_FLOAT"
  };
}

